# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmoketest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminPage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Admin").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".admin-main").click()
    self.driver.find_element(By.ID, "password").send_keys("querty123")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
  
  def test_directoryPage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Directory").click()
    self.driver.find_element(By.ID, "directory-grid").click()
    self.driver.find_element(By.CSS_SELECTOR, "section:nth-child(8) > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "section:nth-child(3) > img").click()
    self.driver.find_element(By.ID, "directory-list").click()
    self.driver.find_element(By.CSS_SELECTOR, "section:nth-child(3)").click()
  
  def test_homePage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-logo img").click()
    self.driver.find_element(By.ID, "nopad").click()
    self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 > .centered-image").click()
    element = self.driver.find_element(By.LINK_TEXT, "Quick Tools")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
  def test_joinPage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(968, 528)
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("Jose")
    self.driver.find_element(By.NAME, "lname").send_keys("Rivera")
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("Martinez")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").send_keys("CEO")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("jym126@hotmail.com")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "cellphone").click()
    self.driver.find_element(By.NAME, "cellphone").send_keys("208 458 2254")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "fieldset").click()
    self.driver.find_element(By.CSS_SELECTOR, ".myradio:nth-child(13)").click()
  
